### ISSUE TITLE
배송지 정보 도로명 주소 API 사용하기

### ISSUE THREAD

**Issue by probitanima11** [Helibrothers/dico-server#125]
# 사용할 도로명 주소 API 체험 사이트
https://www.juso.go.kr/CommonPageLink.do?link=/addrlink/devAddrLinkRequestSample
( 페이지 위 쪽에 있는 팝업 API 활용에서 테스트 해보면 됩니당 )

**Comment by probitanima11** [comment]
![image](https://cloud.githubusercontent.com/assets/4353846/22790571/fc6beede-ef29-11e6-9399-49c2f98bd0e5.png)

**Comment by probitanima11** [comment]
## 남은 작업
- API 사용 신청
  - 현재는 샘플 키로 작업했습니다.
  - 신청하려면 도메인을 입력해야 하는데 신규 헬리팜 도메인이 아직 결정되지않아서 신청을 못했습니다.
- 2,3,4번 화면 하단에 디자인을 수정이 필요합니다.
  - 2, 3, 4번 화면에서 커스터마이징을 할 수 있는 부분은 아래 CSS 파일에 주석으로 달아놨습니다.
  - 이 CSS를 적용하려면 신청하면서 CSS파일을 제출해야 하는데 API 사용 신청과 같이 진행하겠습니다.
```css
/* 바탕 배경 이미지 */
.pop-address-search .pop-address-search-inner { background-image: url(http://www.0000.com/img/backImg.png);}
/* 회사 로고 이미지 */
.pop-address-search .pop-address-search-inner .logo { background: url(http://www.0000.com/img/logo.png) no-repeat; background-position:center; }

/* 바탕 배경색상 */
.pop-address-search .pop-address-search-inner { background-color:#ECECEC; }
/* 검색창 색상 */
.pop-address-search .pop-address-search-inner .wrap input { background-color:#FFFFFF; }
/* 검색버튼 색상 */
.pop-address-search .pop-address-search-inner .wrap { background-color:#FFFFFF; }
/* 본문 배경색(홀수) */
.pop-address-search .pop-address-search-inner .result table.data-col tbody tr:nth-child(odd) td {background:#FFFFFF}
/* 본문 배경색(짝수) */
.pop-address-search .pop-address-search-inner .result table.data-col tbody tr:nth-child(even) td {background:#FFFFFF}
```
 
## 해당 이슈에서 다루지 않을 부분
- 문자로 된 주소값 이외에 행정코드, 좌표 등의 정보를 DB에 저장
  - 이 부분은 주소 관련 DB 설계가 정해진 후 별도의 이슈로 진행하겠습니다.
